production:
  adapter: em_mysql2
  encoding: utf8mb4
  reconnect: false
  pool: 5
  database: backend
  username: backend
  password: 'ba6af5e27fcceca'
  host: 10.121.42.214
  port: 3306

development:
  adapter: em_mysql2
  encoding: utf8mb4
  reconnect: false
  database: ebdb
  pool: 5
  username: root
  password: 'lib217217'
  host: localhost
  port: 3306

test:
  adapter: em_mysql2
  encoding: utf8mb4
  reconnect: false
  database: ebdb
  pool: 5
  username: root
  password: 'lib217217'
  host: localhost
  port: 3306
