production:
  adapter: em_mysql2
  host: 10.121.42.214
  encoding: utf8mb4
  reconnect: true
  pool: 5
  database: backend
  username: backend
  password: '9844340557a75d2'
  port: 3306

development:
  adapter: em_mysql2
  encoding: utf8mb4
  reconnect: true
  database: backend
  pool: 5
  username: root
  password: 'lib217217'
  host: localhost
  port: 3306

test:
  adapter: em_mysql2
  encoding: utf8mb4
  reconnect: true
  database: ebdb
  pool: 5
  username: root
  password: 'lib217217'
  host: localhost
  port: 3306
